kind: Deployment
apiVersion: apps/v1
metadata:
  name: devcraftsman-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcraftsman-ui
  template:
    metadata:
      labels:
        app: devcraftsman-ui
    spec:
      containers:
        - name: devcraftsman-ui
          image: $DOC_USERNAME/$REPOSITORY_URI:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: devcraftsman-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: devcraftsman-ui